name: Validation Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  code_quality_check:
    uses: ./.github/workflows/code_quality_check.yml